const WIDTH_AVATAR = 180;
const HEIGHT_AVATAR = 250;

const HEIGHT_AVATAR_MAX = 600;
const WIDTH_AVATAR_MAX = 450;

const MARGIN_AVATAR = 150;
const HEIGHT_DESCRIPTION = 265;
const HEIGHT_DESCRIPTION_MOBILE = 320;

const POINT_SHOW_TEXT_ABOUT = 0.8;
const POINT_SHOW_TEXT_ABOUT_MOBILE = 0.6;

const HEIGHT_AVATAR_MOBILE_MAX = 450;
const HEIGHT_AVATAR_MOBILE_MIN = 225;

export {
  WIDTH_AVATAR,
  HEIGHT_AVATAR,
  MARGIN_AVATAR,
  HEIGHT_DESCRIPTION,
  WIDTH_AVATAR_MAX,
  HEIGHT_AVATAR_MAX,
  POINT_SHOW_TEXT_ABOUT,
  HEIGHT_DESCRIPTION_MOBILE,
  HEIGHT_AVATAR_MOBILE_MAX,
  HEIGHT_AVATAR_MOBILE_MIN,
  POINT_SHOW_TEXT_ABOUT_MOBILE
};
