const WIDTH_AVATAR = 180;
const HEIGHT_AVATAR = 250;

const HEIGHT_AVATAR_MAX = 600;
const WIDTH_AVATAR_MAX = 450;

const MARGIN_AVATAR = 150;
const HEIGHT_DESCRIPTION = 265;

const POINT_SHOW_TEXT_ABOUT = 0.8;

export {
  WIDTH_AVATAR,
  HEIGHT_AVATAR,
  MARGIN_AVATAR,
  HEIGHT_DESCRIPTION,
  WIDTH_AVATAR_MAX,
  HEIGHT_AVATAR_MAX,
  POINT_SHOW_TEXT_ABOUT
};
