const MAX_WIDTH_BOX = 500;
const MIN_WIDTH_BOX = 400;

const MIN_FONT = "40px";
const MAX_FONT = "100px";

const MIN_HEIGHT_SVG = "30px";
const MAX_HEIGHT_SVG = "86px";

const MIN_WIDTH_TEXT_RIGHT_TOP = 155; // width text HUYNE
const MAX_WIDTH_TEXT_RIGHT_TOP = 500; // width text HUYNE

const MARGIN_TOP_TEXT_RIGHT = 20;

const MARGIN_BOTTOM_MIDDLE_BOX = 120;

const TOTAL_HEIGHT_TEXT = 200; // height total 2 line text HELLO + WEB

export {
  MAX_WIDTH_BOX,
  MIN_WIDTH_BOX,
  MIN_FONT,
  MAX_FONT,
  MIN_HEIGHT_SVG,
  MAX_HEIGHT_SVG,
  MIN_WIDTH_TEXT_RIGHT_TOP,
  MAX_WIDTH_TEXT_RIGHT_TOP,
  MARGIN_TOP_TEXT_RIGHT,
  MARGIN_BOTTOM_MIDDLE_BOX,
  TOTAL_HEIGHT_TEXT
};
